version: '3'

services:

  nginx:
    build:
      context: docker/nginx
    container_name: nginx
    restart: always
    ports: 
      - '8080:80'
    depends_on:
      - app
    networks:
      - app-network

  app:
    build:
      context: docker/node
    container_name: app
    networks: 
      - app-network
    volumes:
      - .:/app
    tty: true
    depends_on:
      - db

  db:
    build:
      context: docker/mysql
    command: --innodb-use-native-aio=0
    container_name: db
    tty: true
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root 
    networks: 
      - app-network

networks: 
  app-network:
    driver: bridge      